---
output:
  pdf_document: default
  html_document: default
  word_document: default
---
# Marco Metodológico {#intro}

En este acápite, se detalla la metodología utilizada y que soporta la validez del estudio y sus resultados. Se especifica el tipo de muestra con sus parámetros propios y el tipo de instrumento aplicado.

## Diseño de la Muestra {#requisitos}

En este estudio, el universo válido corresponderá a los estudiantes de todas las carreras del Instituto, sean estos vespertinos o diurnos y sean de educación en una modalidad presencial y/o virtual. Los resultados de esto últimos estudiantes se analizan en un documento diferente dado que el instrumento es distinto. Otros atributos que poseen los sujetos para ser parte de la muestra son los siguientes:

+	Deben tener matrícula vigente hasta la fecha de aplicación.
+	Su estado como alumnos debe ser *regular*.

Para el cálculo del tamaño de la muestra se ha hecho uso de la fórmula de muestreo aleatorio simple para proporciones, operando con un 95% de confianza, usando una varianza máxima de proporciones (p=0,5 y q=0,5). El error muestral asciende al 4,5% para cada una de las sedes. Esto da como resultado una muestra de 1.243 estudiantes a nivel del Instituto, y un error muestral de un 2,1% a nivel del mismo.


| Sedes | Matrícula 2018 |  Muestra 2018-2 |
| :------- | :------: | :------: |
| Santiago   | 1.819  | 541  | 
| Viña del Mar  | 258 | 151  | 
| Rancagua   | 397    | 188  |
| Concepción   | 299  | 150  |
| Temuco   | 418     |  213  |
| **Total**   | **3.191**  | **1.243**|

La base de datos utilizada para el cálculo de las muestras incorpora, como datos de contacto, el correo electrónico de los alumnos. Mediante este correo se hará el contacto con ellos(as) para que accedan al formulario online (cuestionario) y así entreguen la información solicitada. Además, y para asegurar la eficacia de la estrategia, se considera la colaboración de las direcciones de las sedes del IGS que participan del estudio.

## Diseño del Instrumento

El instrumento utilizado para medir la satisfacción del estudiante considera tanto preguntas cerradas (con opciones de respuestas), como además de preguntas abiertas que permiten registrar la percepción y experiencia de los estudiantes. Todo ello en búsqueda de conocer, describir y medir la percpecion de los estudiantes frente a actores, espacios y servicios varios.

En esta oportunidad, la aplicación del cuestionario se efectuó mediante la plataforma web SurveyMonkey. El proceso implica hacer una invitación a la muestra seleccionada vía correo electrónico, el plazo para responder fue desde el 10 de noviembre hasta el 23 de octubre de 2018.

