# Conclusiones

+ En materia de percepción general, se aprecia que en el año actual la satisfacción neta con los **servicios entregados** alcanza 51%, así como en **calidad de la atención** se alcanza el 63%. En ambos casos, este dato es superior a las últimas mediciones realizadas. A nivel de sedes, se aprecia que el desempeño del primer indicador es superio en las sedes de Temuco(67%) y Viña del Mar(65%), por el contrario, resultó más bajo en Santiago (36%) y Concepción (52%). En cuanto a la Calidad de la atención, también resulta alto en Rancagua (80%) y Viña del Mar (79%), el más bajo es Santiago (46%). Si bien en esta última sede es bajo, el valor ha venido de forma sostenda mejorando.

+ En materia de percepción general, sobresale la disposición positiva por recomendar el instituto, así se alcanzó que un 46% dice que probablemente sí lo haría, y un 40%, dice que *definitivamente* sí lo haría. Esta última categoría no deja dudas respecto de la satisfacción positiva con el instituto, y su valor alcanzado en 2018-2(40%), es superior a los años anteriores.

+ Otro aspecto clave de evaluar corresponde a los **Docentes**. En este ámbito, se aprecia que la satisfacción neta alcanza un 64% en 2018-2. Este valor es superior en 9 puntos respecto de la medición anterior (55%).A nivel de Sede, destaca el valor 2018-2 que se registra en Rancagua y Temuco, ambos con 79%. El valor es más bajo en Concepción (71%) y Santiago (49%).

+ En cuanto a los servicios asociados con **espacios físicos**, se aprecia que el desempeño del espacio de *biblioteca* (física) ha mejorado su desempeño desde la medición de 2017-1, incluso en 2018-1 supera en más de 10 puntos a los otros espacios de atención. Por el contrario, el *casino/cafetería* es el espacio con una menor magnitud de satisfacción neta, tanto a nivel histórico como en cada una de las sedes. Incluso, en este mismo ámbito, se constata una baja desde 2017-2 a 2018-2, pasando del 25% al 14%.

+ En cuanto a los **servicios digitales o virtuales**, se puede apreciar que *Ebook* (biblioteca virtual) ha venido mejorando medición tras medición, llegando en la última mediicón a 74%. Por otra parte, los estudiantes tienen una percepción positiva de *IEB Virtual*, así la satisfacción neta no baja del 70%. En este ámbito, el servicio de *WIFI* es aquel que tiene una evaluación más negativa, especialmente en la medición 2017-1 éste valor es negativo (-22%), ahora bien, este indicador ha mejorado desde dicha medición, alcanzando en la última medición los 54% puntos porcentuales. 

+ En relación con servicios como **cajas**, se puede apreciar que éste ámbito ha venido mejorando en la percpecion de los estudiantes. De esta forma, en la medición de 2015-2 alcanza el 19%, pero ya desde ese punto se genera un punto de inflexión al alza que se sostiene y llega en 2018-2 al 71% en la última medición. Otro servicio evaluado, corresponde al **servicio de solicitudes**, servicio que es evaluado de forma irregular en el tiempo, tendiendo a una baja significativa en la medición 2016-1, de ahí sube en 2017-1 a 58%, pero desciende nuevamente en 2018-1 (46%) y vuelve a subir en 2018-2 a 61%.


